import { Agent } from './Agent';
import { Analysis } from './Analysis';
import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Chart, number, time } from './Chart';
import type { Alert, Candle, Market, Portfolio, Realtime, Ticker, Watch } from './types';
import './style.css';

interface AlertLog { id:string; market:string; condition:string; triggerPrice:string; triggeredAt:string; notificationStatus:string }
type Page = 'dashboard'|'portfolio'|'alerts';
class ApiError extends Error { constructor(message: string, public status: number) { super(message); } }
async function api<T>(path: string, method = 'GET', body?: unknown, token?: string): Promise<T> {
  const response = await fetch(path, { method, credentials: 'same-origin', headers: { ...(body ? {'Content-Type':'application/json'} : {}), ...(token ? {'X-Monitor-Token':token} : {}) }, body: body ? JSON.stringify(body) : undefined, signal: AbortSignal.timeout(60000) });
  if (response.status === 204) return undefined as T;
  const data = await response.json();
  if (!response.ok) {
    const messages: Record<number,string> = {401:'연결이 필요합니다. 로컬 접근 토큰을 확인해 주세요.',409:'이미 관심 종목에 등록되어 있습니다.',503:'데이터 연결을 사용할 수 없습니다. 잠시 후 다시 시도해 주세요.',502:'거래소 데이터를 가져오지 못했습니다.'};
    throw new ApiError(messages[response.status] || (typeof data.message === 'string' ? data.message : '요청을 처리하지 못했습니다.'), response.status);
  }
  return data;
}
function Icon({name}: {name:string}) {
  const paths: Record<string,string> = { grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',wallet:'M3 6h17v14H3z M3 6V3h14v3 M15 11h6v5h-6z',bell:'M5 17h14l-2-4V9a5 5 0 0 0-10 0v4z M10 21h4',pulse:'M2 13h4l3-8 5 15 3-7h5',arrow:'M4 12h16 M14 6l6 6-6 6',refresh:'M20 8a8 8 0 1 0 1 7 M20 3v6h-6',plus:'M12 4v16 M4 12h16',logout:'M9 3H4v18h5 M13 7l5 5-5 5 M8 12h10'};
  return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name] || paths.pulse}/></svg>;
}
const emptyLive: Realtime = { status:'idle',subscriptions:[],cacheHealthy:true,receivedCount:0,lastMessageAt:null,tickers:[],activeAlertCount:0 };
function App() {
  const [page,setPage] = useState<Page>('dashboard');
  const [authenticated,setAuthenticated] = useState(false);
  const [login,setLogin] = useState(false), [token,setToken] = useState('');
  const [busy,setBusy] = useState(false), [message,setMessage] = useState('');
  const [markets,setMarkets] = useState<Market[]>([]), [selected,setSelected] = useState('KRW-BTC');
  const [timeframe,setTimeframe] = useState('1h'), [candles,setCandles] = useState<Candle[]>([]), [ticker,setTicker] = useState<Ticker|null>(null);
  const [analysisRefresh,setAnalysisRefresh] = useState(0);
  const [chartBusy,setChartBusy] = useState(true), [chartError,setChartError] = useState('');
  const [watchlist,setWatchlist] = useState<Watch[]>([]), [alerts,setAlerts] = useState<Alert[]>([]);
  const [logs,setLogs] = useState<AlertLog[]>([]);
  const [live,setLive] = useState<Realtime>(emptyLive), [streamUp,setStreamUp] = useState(false);
  const [portfolio,setPortfolio] = useState<Portfolio|null>(null), [portfolioBusy,setPortfolioBusy] = useState(false), [portfolioError,setPortfolioError] = useState('');
  const [watchInput,setWatchInput] = useState('BTC');
  const [alertOpen,setAlertOpen] = useState(false), [editing,setEditing] = useState<string|null>(null);
  const [alertMarket,setAlertMarket] = useState('KRW-BTC'), [condition,setCondition] = useState<'BELOW'|'ABOVE'>('BELOW'), [target,setTarget] = useState(''), [once,setOnce] = useState(true), [cooldown,setCooldown] = useState('60');
  const chartGeneration = useRef(0), portfolioGeneration = useRef(0), stateGeneration = useRef(0);
  const selectedLive = live.tickers.find(row=>row.market===selected);
  const selectedMeta = markets.find(row=>row.market===selected);
  const liveFresh = streamUp && live.status === 'connected' && selectedLive && Date.now()-Date.parse(selectedLive.receivedAt)<60000;
  const current = liveFresh ? selectedLive.price : ticker?.price;
  function fail(error: unknown) { if (error instanceof ApiError && error.status===401) setAuthenticated(false); setMessage(error instanceof Error ? error.message : '오류가 발생했습니다.'); }
  async function refreshState() { const generation=stateGeneration.current; const [w,a,l] = await Promise.all([api<Watch[]>('/watchlist'),api<Alert[]>('/alerts'),api<AlertLog[]>('/alerts/logs')]);if(generation===stateGeneration.current){setWatchlist(w);setAlerts(a);setLogs(l);} }
  async function action(run:()=>Promise<unknown>, success?:string) { if(busy)return;setBusy(true);try {await run();if(success)setMessage(success);}catch(e){fail(e);}finally{setBusy(false);} }
  async function loadChart() {
    setAnalysisRefresh(v=>v+1);
    const generation=++chartGeneration.current;setChartBusy(true);setChartError('');
    try { const [t,c]=await Promise.all([api<Ticker>(`/market/${selected}/ticker`),api<Candle[]>(`/market/${selected}/candles?timeframe=${timeframe}&limit=100`)]);if(generation===chartGeneration.current){setTicker(t);setCandles(c);} }
    catch(e){if(generation===chartGeneration.current){setTicker(null);setCandles([]);setChartError(e instanceof Error?e.message:'차트 조회 실패');}}
    finally{if(generation===chartGeneration.current)setChartBusy(false);}
  }
  async function loadPortfolio() {
    const generation=++portfolioGeneration.current;setPortfolioBusy(true);setPortfolioError('');
    try{const data=await api<Portfolio>('/portfolio');if(generation===portfolioGeneration.current)setPortfolio(data);}
    catch(e){if(generation===portfolioGeneration.current){setPortfolioError(e instanceof Error?e.message:'자산 조회 실패');if(e instanceof ApiError&&e.status===401)setAuthenticated(false);}}
    finally{if(generation===portfolioGeneration.current)setPortfolioBusy(false);}
  }
  useEffect(()=>{void api<Market[]>('/markets').then(setMarkets).catch(fail);void api<{authenticated:boolean}>('/session').then(s=>setAuthenticated(s.authenticated)).catch(fail);},[]);
  useEffect(()=>{setTicker(null);setCandles([]);void loadChart();},[selected,timeframe]);
  useEffect(()=>{
    if(!authenticated){stateGeneration.current++;portfolioGeneration.current++;setPortfolio(null);setPortfolioBusy(false);setPortfolioError('');setWatchlist([]);setAlerts([]);setLogs([]);setLive(emptyLive);return;}
    let active=true;
    void refreshState().catch(fail);
    const refreshTimer=setInterval(()=>{void refreshState().catch(fail);},10000);
    const events=new EventSource('/realtime/stream');
    events.onmessage=e=>{if(active){try{setLive(JSON.parse(e.data));setStreamUp(true);}catch{setStreamUp(false);}}};
    events.onerror=()=>{if(active)setStreamUp(false);};
    return()=>{active=false;clearInterval(refreshTimer);events.close();setStreamUp(false);};
  },[authenticated]);
  useEffect(()=>{if(page==='portfolio'&&authenticated)void loadPortfolio();},[page,authenticated]);
  useEffect(()=>{if(message){const timer=setTimeout(()=>setMessage(''),6500);return()=>clearTimeout(timer);}},[message]);
  function requireLogin(run:()=>void) { if(!authenticated)setLogin(true);else run(); }
  function openAlert(row?:Alert) {requireLogin(()=>{setEditing(row?.id??null);setAlertMarket(row?.market??selected);setCondition(row?.condition??'BELOW');setTarget(row?.targetPrice??'');setOnce(row?.triggerOnce??true);setCooldown(String(row?.cooldownMinutes??60));setAlertOpen(true);});}
  async function saveAlert(e:React.FormEvent) {e.preventDefault();await action(async()=>{await api(editing?`/alerts/${editing}`:'/alerts',editing?'PATCH':'POST',{market:alertMarket,condition,targetPrice:target,triggerOnce:once,cooldownMinutes:Number(cooldown)});await refreshState();setAlertOpen(false);},'알림 조건을 저장했습니다. 조건 충족 시 Discord로 발송합니다.');}
  const connected=authenticated&&streamUp&&live.status==='connected';
  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="/" aria-label="Crypto Monitor 홈"><span className="brand-mark"><Icon name="pulse"/></span><span>crypto<span className="brand-light">monitor</span></span></a><div className="workspace-label">PERSONAL WORKSPACE</div>
      <nav>{([['dashboard','grid','대시보드'],['portfolio','wallet','포트폴리오'],['alerts','bell','가격 알림']] as const).map(([key,icon,label])=><button className={`nav-item ${page===key?'active':''}`} onClick={()=>setPage(key)} key={key}><Icon name={icon}/>{label}{key==='alerts'&&alerts.length>0&&<span className="count">{alerts.length}</span>}</button>)}</nav>
      <div className="sidebar-note"><div className="tiny-dot"/> 나만의 로컬 모니터<div>데이터는 내 Mac에.<br/>관찰은 차분하게.</div></div>
      <div className="profile"><div className="avatar">M</div><div><strong>My workspace</strong><small>개인용 · 읽기 전용</small></div><span className="profile-dot"/></div>
    </aside>
    <main><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> {page==='dashboard'?'Overview':page==='portfolio'?'Portfolio':'Price alerts'}</div><div className="top-actions"><span className="local-pill"><i/> LOCAL</span>{authenticated?<button className="text-button" onClick={()=>void action(async()=>{await api('/session','DELETE');setAuthenticated(false);})}><Icon name="logout"/>연결 해제</button>:<button className="connect-button" onClick={()=>setLogin(true)}>내 워크스페이스 연결 <Icon name="arrow"/></button>}</div></header>
      <div className="page-content"><div className="page-heading"><div><div className="eyebrow">YOUR CRYPTO, IN PERSPECTIVE</div><h1>{page==='dashboard'?'시장을 한눈에.':page==='portfolio'?'나의 포트폴리오.':'놓치지 않을 가격.'}</h1><p>{page==='dashboard'?'관심 있는 움직임을 모으고, 내 기준으로 시장을 살펴보세요.':page==='portfolio'?'현재 보유 자산과 원화 평가액을 차분히 확인하세요.':'원하는 가격 조건을 저장하고 실시간 구독 상태를 확인하세요.'}</p></div><div className="date-chip">{new Date().toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'long'})}<small>Asia / Seoul</small></div></div>
      {page==='dashboard'&&<>
        <div className="stats-grid"><section className="stat-card"><div className="stat-label">관심 종목 <Icon name="grid"/></div><div className="stat-value">{authenticated?watchlist.filter(w=>w.enabled).length:'—'}<small>종목</small></div><div className="stat-caption">내가 선택한 시장의 움직임</div></section><section className="stat-card"><div className="stat-label">실시간 연결 <Icon name="pulse"/></div><div className="stat-value connection-text"><i className={connected?'dot green':'dot'}/>{connected?'연결됨':authenticated&&live.subscriptions.length?'연결 중':authenticated?'구독 대기':'연결 전'}</div><div className="stat-caption">{connected?`${live.subscriptions.length}개 시장 · 단일 WebSocket`:'관심 종목 또는 알림 종목을 등록하세요'}</div></section><section className="stat-card orange-tint"><div className="stat-label">저장된 알림 조건 <Icon name="bell"/></div><div className="stat-value">{authenticated?alerts.filter(a=>a.enabled).length:'—'}<small>개</small></div><div className="stat-caption">{live.notificationEngineEnabled?'Discord 가격 알림 사용 중':'Discord 웹후크 설정 필요'}</div></section></div>
        <section className="panel market-panel"><div className="panel-header"><div><h2>시장 탐색 <span className="exchange-pill">BITHUMB</span></h2><p>가격의 흐름을 살펴보세요</p></div><select aria-label="조회할 시장" className="market-select" value={selected} onChange={e=>setSelected(e.target.value)}>{!markets.length&&<option value="KRW-BTC">비트코인 · BTC</option>}{markets.map(m=><option key={m.market} value={m.market}>{m.koreanName} · {m.market}</option>)}</select></div>
          <div className="price-toolbar"><div className="coin-heading"><div className={`coin-icon ${selected.endsWith('BTC')?'bitcoin':''}`}>{selected.endsWith('BTC')?'₿':selected.split('-')[1].slice(0,1)}</div><div><h3>{selectedMeta?.koreanName??selected.split('-')[1]} <span>{selected}</span></h3><div className="big-price">{selected.startsWith('KRW')?'₩':''}{chartBusy&&!liveFresh?'—':number(current,selected.startsWith('KRW')?2:8)} <span className="price-unit">{selected.split('-')[0]}</span></div></div></div><div className="price-metrics"><div><span>최근 24시간</span><b className={(ticker?.change24h??0)>=0?'positive':'negative'}>{ticker?.change24h==null?'—':`${ticker.change24h>0?'+':''}${number(ticker.change24h,2)}%`}</b></div><div><span>24시간 거래량</span><b>{number(liveFresh?selectedLive.volume24h:ticker?.volume24h,2)}</b></div><span className={`source-badge ${liveFresh?'live':''}`}>{liveFresh?'● LIVE':'REST 조회'}</span></div></div>
          <div className="chart-controls"><div className="timeframes">{['1m','5m','15m','1h','4h','1d'].map(t=><button key={t} onClick={()=>setTimeframe(t)} className={t===timeframe?'selected':''}>{t}</button>)}</div><button className="text-button" disabled={chartBusy} onClick={()=>void loadChart()}><Icon name="refresh"/>새로고침</button></div>
          {chartError?<div className="inline-error">{chartError}<button onClick={()=>void loadChart()}>다시 시도</button></div>:chartBusy?<div className="chart-empty"><span className="spinner"/>시장 데이터를 가져오고 있습니다</div>:<Chart rows={candles}/>}
          <div className="chart-footer"><span>캔들·24시간 지표는 조회 시 갱신 · KST · 마지막 봉 진행 중 가능</span><button className="text-button accent" onClick={()=>openAlert()}>이 종목 알림 조건 추가 <Icon name="plus"/></button></div></section>
        <Analysis market={selected} timeframe={timeframe} refresh={analysisRefresh}/>
        <section className="panel"><div className="panel-header"><div><h2>나의 관심 종목</h2><p>한 번의 연결로, 필요한 시장만</p></div><form className="inline-form" onSubmit={e=>{e.preventDefault();requireLogin(()=>void action(async()=>{await api('/watchlist','POST',{market:watchInput});await refreshState();},'관심 종목을 추가했습니다.'));}}><input aria-label="추가할 관심 종목" list="market-codes" value={watchInput} onChange={e=>setWatchInput(e.target.value)} placeholder="BTC 또는 KRW-BTC"/><button className="primary small" disabled={busy}><Icon name="plus"/>추가</button></form></div>
          {!authenticated?<div className="empty-state"><Icon name="wallet"/><h3>나의 시장을 연결하세요</h3><p>로컬 접근 토큰으로 관심 종목과 보유 자산을 안전하게 확인합니다.</p><button className="secondary" onClick={()=>setLogin(true)}>워크스페이스 연결</button></div>:!watchlist.length?<div className="empty-state"><h3>첫 관심 종목을 추가해 보세요</h3><p>위 입력란에 BTC, ETH 등 원하는 종목을 입력하세요.</p></div>:<div className="table-wrap"><table><thead><tr><th>종목</th><th>실시간 가격</th><th>전일 대비</th><th>수신 상태</th><th>관리</th></tr></thead><tbody>{watchlist.map(w=>{const row=live.tickers.find(t=>t.market===w.market);const fresh=connected&&row&&Date.now()-Date.parse(row.receivedAt)<60000;return <tr key={w.id}><td><button className="market-link" onClick={()=>{setSelected(w.market);window.scrollTo({top:0,behavior:'smooth'});}}><span className="mini-coin">{w.market.split('-')[1][0]}</span><span><strong>{markets.find(m=>m.market===w.market)?.koreanName??w.market}</strong><small>{w.market}</small></span></button></td><td className="numeric">{w.market.startsWith('KRW')?'₩':''}{number(row?.price,8)}</td><td className={(row?.changeRate??0)>=0?'positive':'negative'}>{row?`${row.changeRate>0?'+':''}${number(row.changeRate*100,2)}%`:'—'}</td><td><span className={`badge ${fresh?'green-badge':''}`}>{!w.enabled?'일시 정지':fresh?'실시간':'수신 대기 / 지연'}</span></td><td><div className="row-actions"><button disabled={busy} onClick={()=>void action(async()=>{await api(`/watchlist/${w.id}`,'PATCH',{enabled:!w.enabled});await refreshState();})}>{w.enabled?'정지':'재개'}</button><button className="danger-text" disabled={busy} onClick={()=>void action(async()=>{await api(`/watchlist/${w.id}`,'DELETE');await refreshState();},'관심 종목을 삭제했습니다.')}>삭제</button></div></td></tr>;})}</tbody></table></div>}
        </section>
      </>}
      {page==='portfolio'&&<section className="panel portfolio-panel"><div className="panel-header"><div><h2>보유 자산</h2><p>사용 가능 수량과 묶인 수량을 모두 포함합니다</p></div><button className="secondary" disabled={portfolioBusy} onClick={()=>requireLogin(()=>void loadPortfolio())}><Icon name="refresh"/>자산 새로고침</button></div>{!authenticated?<div className="empty-state"><Icon name="wallet"/><h3>나의 자산은 나에게만</h3><p>워크스페이스를 연결하면 실제 Bithumb 보유 자산을 조회합니다.</p><button className="primary" onClick={()=>setLogin(true)}>워크스페이스 연결</button></div>:portfolioBusy?<div className="chart-empty"><span className="spinner"/>자산을 조회하고 있습니다</div>:portfolioError?<div className="inline-error">{portfolioError}</div>:portfolio&&<><div className="portfolio-summary"><span>{portfolio.valuationComplete?'총 평가액':'확인 가능한 평가액'}</span><strong>₩{number(portfolio.valuationComplete?portfolio.totalAssetKRW:portfolio.knownValueKRW,2)}</strong><small>{time(portfolio.accountsFetchedAt)} KST 기준</small></div>{!portfolio.valuationComplete&&<div className="notice">일부 자산의 시세를 확인할 수 없어 전체 평가액과 비중을 계산하지 않았습니다. 보유 수량은 그대로 표시됩니다.</div>}<div className="table-wrap"><table><thead><tr><th>자산</th><th>총 보유량</th><th>평가액</th><th>평가 손익</th><th>비중</th></tr></thead><tbody>{portfolio.assets.map(a=><tr key={a.currency}><td><strong>{a.currency}</strong>{a.pricingUnavailableReason&&<small className="muted">{a.pricingUnavailableReason==='NO_SUPPORTED_MARKET'?'평가 가능한 시장 없음':'시세 조회 불가'}</small>}</td><td>{number(a.balance,10)}{a.locked>0&&<small className="muted">묶인 수량 {number(a.locked,10)}</small>}</td><td>{a.valuation==null?'평가 불가':`₩${number(a.valuation,2)}`}</td><td className={a.profit==null?'muted':a.profit>=0?'positive':'negative'}>{a.profit==null?'원금 정보 부족':`₩${number(a.profit,2)}`}<small>{a.profitRate==null?'':`${number(a.profitRate,2)}%`}</small></td><td>{a.portfolioWeight==null?'—':`${number(a.portfolioWeight,2)}%`}</td></tr>)}</tbody></table>{!portfolio.assets.length&&<div className="empty-state">보유 자산이 없습니다.</div>}</div></>}</section>}
      {page==='alerts'&&<section className="panel"><div className="panel-header"><div><h2>가격 알림 조건 <span className="exchange-pill">{alerts.length}</span></h2><p>원하는 가격을 내 기준으로 설정하세요</p></div><button className="primary" onClick={()=>openAlert()}><Icon name="plus"/>조건 추가</button></div><div className="notice">조건 충족 시 Discord로 알립니다. 1회 알림은 발생 후 정지하며, 반복 알림은 대기 시간 이후 조건을 다시 확인합니다. 이미 조건을 만족한 상태에서도 알림이 발생합니다.</div>{!authenticated?<div className="empty-state"><h3>저장한 조건을 확인하려면 연결하세요</h3><button className="secondary" onClick={()=>setLogin(true)}>워크스페이스 연결</button></div>:!alerts.length?<div className="empty-state"><Icon name="bell"/><h3>관심 있는 가격을 정해 보세요</h3><p>설정한 종목은 관심 목록에서 삭제해도 구독을 유지합니다.</p><button className="secondary" onClick={()=>openAlert()}>첫 알림 조건 추가</button></div>:<div className="table-wrap"><table><thead><tr><th>종목 / 조건</th><th>설정 가격</th><th>반복 설정</th><th>구독 사용</th><th>관리</th></tr></thead><tbody>{alerts.map(a=><tr key={a.id}><td><strong>{a.market}</strong><small>{a.condition==='BELOW'?'설정 가격 이하 ≤':'설정 가격 이상 ≥'}</small></td><td className="numeric">{a.market.startsWith('KRW')?'₩':''}{number(Number(a.targetPrice),10)}</td><td>{a.triggerOnce?'1회':`${a.cooldownMinutes}분 간격`}</td><td><button className={`badge toggle ${a.enabled?'green-badge':''}`} disabled={busy} onClick={()=>void action(async()=>{await api(`/alerts/${a.id}`,'PATCH',{enabled:!a.enabled});await refreshState();})}>{a.enabled?'사용 중':'정지'}</button></td><td><div className="row-actions"><button onClick={()=>openAlert(a)}>수정</button><button className="danger-text" disabled={busy} onClick={()=>void action(async()=>{await api(`/alerts/${a.id}`,'DELETE');await refreshState();},'알림 조건을 삭제했습니다.')}>삭제</button></div></td></tr>)}</tbody></table></div>}</section>}
      {page==='alerts'&&authenticated&&<section className="panel"><div className="panel-header"><h2>알림 발생 이력</h2><button className="secondary" onClick={()=>void action(refreshState)}>새로고침</button></div><div className="notice">발송 실패는 미전송 또는 수신 확인 실패입니다. 처리 중이 오래 지속되면 발송 결과가 불확실할 수 있습니다. 중복 방지를 위해 자동 재전송하지 않습니다.</div><div className="table-wrap"><table><thead><tr><th>발생 시각 (KST)</th><th>종목</th><th>도달 가격</th><th>Discord</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{time(l.triggeredAt)}</td><td>{l.market}</td><td>{number(Number(l.triggerPrice),10)}</td><td>{l.notificationStatus==='SENT'?'발송 완료':l.notificationStatus==='FAILED'?'발송 실패 / 확인 불가':'처리 중 / 확인 필요'}</td></tr>)}</tbody></table>{!logs.length&&<div className="empty-state">발생한 알림이 없습니다.</div>}</div></section>}
      {authenticated&&page!=='alerts'&&<Agent key={`${page}-${selected}-${timeframe}`} market={selected} timeframe={timeframe} portfolio={page==='portfolio'}/>}
      <footer className="page-footer"><span><i className="tiny-dot"/> Bithumb Public API · 내 Mac에서 실행 중</span><span>Monitoring only. No trading.</span></footer>
      {authenticated&&!live.cacheHealthy&&<div className="notice">설정 동기화에 실패했습니다. 마지막 구독을 유지하며 재시도하고 있습니다.</div>}
      </div>
    </main>
    <datalist id="market-codes">{markets.map(m=><option key={m.market} value={m.market}>{m.koreanName}</option>)}</datalist>
    {message&&<div className="toast" role="status">{message}<button aria-label="메시지 닫기" onClick={()=>setMessage('')}>×</button></div>}
    {login&&<div className="modal-backdrop" onClick={()=>{if(!busy){setLogin(false);setToken('');}}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="login-title" onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="연결 창 닫기" onClick={()=>{setLogin(false);setToken('');}}>×</button><div className="modal-icon"><Icon name="wallet"/></div><h2 id="login-title">내 워크스페이스 연결</h2><p>로컬 접근 토큰을 입력하세요.<br/>Bithumb API 키나 Secret Key를 입력하지 마세요.</p><form onSubmit={e=>{e.preventDefault();void action(async()=>{await api('/session','POST',undefined,token);setAuthenticated(true);setLogin(false);setToken('');},'워크스페이스에 연결했습니다.');}}><label>로컬 접근 토큰<input type="password" autoFocus autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} required minLength={32} maxLength={256}/></label><div className="field-hint">프로젝트 .env의 PORTFOLIO_API_TOKEN 값입니다.<br/>토큰은 브라우저 저장소에 보관하지 않습니다.</div><button className="primary full" disabled={busy}>{busy?'연결 중…':'안전하게 연결'}</button></form></section></div>}
    {alertOpen&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="alert-title"><button className="modal-close" aria-label="알림 창 닫기" onClick={()=>setAlertOpen(false)}>×</button><div className="modal-icon"><Icon name="bell"/></div><h2 id="alert-title">{editing?'알림 조건 수정':'새로운 가격 조건'}</h2><p>목표 가격을 정하고 모니터링할 종목을 추가하세요.</p><form onSubmit={saveAlert}><label>시장<input required list="market-codes" value={alertMarket} onChange={e=>setAlertMarket(e.target.value)}/></label><div className="form-grid"><label>조건<select value={condition} onChange={e=>setCondition(e.target.value as 'ABOVE'|'BELOW')}><option value="BELOW">설정 가격 이하 ≤</option><option value="ABOVE">설정 가격 이상 ≥</option></select></label><label>목표 가격 ({alertMarket.split('-')[0]||'KRW'})<input required type="number" min="0.0000000001" max="1000000000000000" step="any" value={target} onChange={e=>setTarget(e.target.value)}/></label></div><label className="check-label"><input type="checkbox" checked={once} onChange={e=>setOnce(e.target.checked)}/>한 번만 알림</label>{!once&&<label>재알림 대기 시간 (분)<input required type="number" min="1" max="10080" value={cooldown} onChange={e=>setCooldown(e.target.value)}/></label>}<div className="field-hint">1회 알림은 발송 실패 시에도 정지합니다. 발송 이력을 확인한 후 다시 활성화할 수 있습니다.</div><button className="primary full" disabled={busy}>{busy?'저장 중…':'조건 저장'}</button></form></section></div>}
  </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
