require('reflect-metadata');const {test}=require('node:test');const assert=require('node:assert/strict');const {Logger}=require('@nestjs/common');Logger.overrideLogger(false);
const {GeminiProvider,responseText}=require('../dist/agent/llm.provider');const {AgentService}=require('../dist/agent/agent.service');
const good={candidates:[{finishReason:'STOP',content:{parts:[{text:'관측 데이터: 테스트'}]}}]};
test('Gemini parser rejects partial, blocked and empty outputs',()=>{assert.equal(responseText(good),'관측 데이터: 테스트');for(const v of [{candidates:[{finishReason:'MAX_TOKENS'}]},{candidates:[]},{candidates:[{finishReason:'STOP',content:{parts:[{thought:true,text:'hidden'}]}}]}])assert.throws(()=>responseText(v));});
test('provider sends bounded structured context; sanitizes failures',async()=>{const original=global.fetch;try{
 const p=new GeminiProvider({googleAiStudioApiKey:'private-secret',geminiModel:'gemini-2.5-flash'});
 global.fetch=async(url,o)=>{assert.ok(url.endsWith('gemini-2.5-flash:generateContent'));assert.equal(o.headers['x-goog-api-key'],'private-secret');const b=JSON.parse(o.body);assert.equal(b.generationConfig.maxOutputTokens,4096);assert.ok(b.systemInstruction.parts[0].text.includes('Never fabricate'));assert.equal(b.contents[0].role,'user');return {ok:true,json:async()=>good};};assert.ok(await p.summarize({price:1}));
 global.fetch=async()=>{throw Error('private-secret')};await assert.rejects(p.summarize({}),e=>e.getStatus()===502&&!e.message.includes('private-secret'));
 await assert.rejects(new GeminiProvider({}).summarize({}),e=>e.getStatus()===503);
 }finally{global.fetch=original;}});
function setup(configured=true){let captured,calls=0;const llm={configured,summarize:async c=>{captured=c;calls++;return '관측 데이터\n요약';}};
 const market={getAnalysis:async m=>({market:m,price:100,indicators:{rsi14:50}})};
 const portfolio={getPortfolio:async()=>({valuationComplete:false,totalAssetKRW:null,knownValueKRW:100,accountsFetchedAt:new Date(),unpricedCurrencies:['MISSING'],assets:[{currency:'BTC',balance:999,account:'secret-account',valuation:100,portfolioWeight:null,profitRate:null,pricingStatus:'AVAILABLE',pricingMarkets:['KRW-BTC'],priceTimestamps:[]}]})};
 const db={priceAlert:{findMany:async()=>[{market:'KRW-BTC',condition:'BELOW',targetPrice:95}]},watchlist:{findMany:async()=>[{market:'KRW-BTC'}]}};
 return {service:new AgentService(llm,market,portfolio,db),portfolio,market,stats:()=>({captured,calls})};}
test('portfolio context preserves partial valuation and omits raw balances and identifiers',async()=>{const f=setup();const result=await f.service.summarize('briefing');assert.ok(result.summary);const c=f.stats().captured;assert.equal(c.portfolio.totalAssetKRW,null);assert.equal(c.alerts[0].distancePercent,-5);assert.equal(c.portfolio.assets[0].balance,undefined);assert.equal(c.portfolio.assets[0].account,undefined);assert.equal(c.markets.length,1);await assert.rejects(f.service.summarize('briefing'),e=>e.getStatus()===429);});
test('market summary never fetches private portfolio; missing config makes no calls',async()=>{const f=setup();f.portfolio.getPortfolio=()=>{throw Error('must not call')};await f.service.summarize('market','btc');assert.equal(f.stats().captured.portfolio,null);const g=setup(false);await assert.rejects(g.service.summarize('market','BTC'),e=>e.getStatus()===503);assert.equal(g.stats().calls,0);});
test('failed sources remain explicit; no usable context prevents LLM call',async()=>{const f=setup();f.portfolio.getPortfolio=async()=>{throw Error()};await f.service.summarize('briefing');assert.ok(f.stats().captured.warnings.includes('PORTFOLIO_UNAVAILABLE'));const g=setup();g.market.getAnalysis=async()=>{throw Error()};await assert.rejects(g.service.summarize('market','BTC'),e=>e.getStatus()===503);assert.equal(g.stats().calls,0);});
